### ISSUE TITLE
[macOS] JARCH-Vis does not appear at installation in addons list

### ISSUE THREAD

**Issue by thmrtnz** [BlendingJake/JARCH-Vis#5]
Hello.

I've looked at previous issues to find instructions.

Despite installing the addon following the README/Wiki, it does not appear in addons list.

See screen shots there after.

<img width="1552" alt="screen shot 2019-02-18 at 13 15 50" src="https://user-images.githubusercontent.com/47714003/52950739-55cf7300-3380-11e9-80a9-f748bbccf572.png">
<img width="772" alt="screen shot 2019-02-18 at 13 16 01" src="https://user-images.githubusercontent.com/47714003/52950745-56680980-3380-11e9-8df8-f9e162545845.png">
[system-info.txt](https://github.com/BlendingJake/JARCH-Vis/files/2875546/system-info.txt)

**Comment by schroef** [comment]
@thmrtnz Was blender open when you did this? If so hit that refresh button. Otherwise start blender with a console window. You can do this by right clicking the blender.app than go to > Content > MacOs > blender
See below
<img width="379" alt="screen shot 2019-02-18 at 12 30 11" src="https://user-images.githubusercontent.com/6923008/52964610-16e9ef00-3379-11e9-9d14-fc303818244b.png">

See if any errors show about this addon

EDIT
after checking this init. This addon is not ready for 2.80

**Comment by schroef** [comment]
You can check this branch, i see the dev is working on a update.
https://github.com/BlendingJake/JARCH-Vis/tree/restructure

**Comment by BlendingJake** [comment]
@thmrtnz As @schroef pointed out, I have been working on getting JARCH Vis to work with Blender 2.8. There is currently a pre-release out that supports 2.80, which can be found [here](https://github.com/BlendingJake/JARCH-Vis/releases). 

So a couple questions:

1. How did you download `jarch_vis`? Did you clone the repository, or did you go to `Releases` and download the pre-release that is in there?
1. Did you restart/refresh Blender after copying the `jarch_vis` folder into the addons folder?
1. The folder structure in your first screenshot is a little odd. I am running on Windows, so I'm not sure if that is the issue, but by default, my `addons` folder contains 121 folders and files for Blender 2.80. I'm not sure why yours only has 4 folders. Did you change your `Scripts` or `Addons` path within Blender's User Preferences?
1. Lastly, restart Blender, and go to `Window -> Toggle System Console` and see if there are any errors in there related to `jarch_vis`.

**Comment by thmrtnz** [comment]
1. I downloaded the 2.0.0 release.

2. I restarted Blender multiple times.

3. You are describing the Blender local folder. See 
[Paths](https://docs.blender.org/manual/en/latest/getting_started/installing/configuration/directories.htm
). I am using the USER path, and that's the default behavior of Blender, at least on macOS. The others addons work as expected from there.

There's no error. Blender is blind, like JARCH Vis doesn't exist.

**Comment by BlendingJake** [comment]
Hmm... I have never tested putting it in the USER path, but I just did, and it worked fine on Windows.

1. What is the full release number for the version of Blender you are on?
1. Could you try putting `jarch_vis` in the SYSTEM path instead? Although, that shouldn't make any difference.

**Comment by thmrtnz** [comment]
That's the version of Blender I currently use:

version: 2.80 (sub 44)
branch: blender2.7
commit date: 2019-02-15 14:15
hash: faa255c0a4e4
build date: 2019-02-15, 16:23:20

I joined a system-info.txt in the OP.

It doesn't work in the LOCAL path either.

**Comment by thmrtnz** [comment]
For some unknown reason, on macOS, when you expand the archive JARCH-Vis.2.0.0,
the folder gets a hidden .0 extension. 

You have to rename it in the macOS Get Info panel, and then it works.

I should really use the terminal to browse the file system, _ls_ doesn't hide that kind of stuff!

**Comment by BlendingJake** [comment]
I need to change the default naming scheme to just default to `jarch_vis` to make the process easier.

I'll try and get ahold of a build around that one and see if I can replicate on Windows.

**Comment by schroef** [comment]
Its shows an almost empty script folder because that is the user script folder. This is where all addon come when you use either install zip or manually add the. On osx all provided addons are within the app it self. You can check them as i explained earlier. Rightclick on the blender.app > show contents. Than browser to the script folder.

But that isnt needed for this addon.

The issue it has that jv_siding is trying to import a something which is not there
```
Traceback (most recent call last):
  File "/Applications/blender-2.80.0-git20190211.b8d4f06b102d-x86_64/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.80/scripts/addons/JARCH-Vis/__init__.py", line 48, in <module>
    from . import jv_types
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.80/scripts/addons/JARCH-Vis/jv_types.py", line 15, in <module>
    from . jv_siding import JVSiding
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.80/scripts/addons/JARCH-Vis/jv_siding.py", line 18, in <module>
    from scipy.spatial import Delaunay
ModuleNotFoundError: No module named 'scipy'
```

I think you should add the script file to your addon. I dont know scipy but seems like a complete lib. You just using one mod

**Comment by schroef** [comment]
PS when you expand the zip it gets the name from repo. I did NOT get JARVIS-Vis.2.0.0.0 
I get the repo name JARCH-Vis-restructure 

I install them manually most of the time. I see using the zip results in a error from blender. Looks like a bug.
```
Traceback (most recent call last):
  File "/Applications/blender-2.80.0-git20190211.b8d4f06b102d-x86_64/blender.app/Contents/Resources/2.80/scripts/startup/bl_operators/userpref.py", line 605, in execute
    module_filesystem_remove(path_addons, f)
NameError: name 'module_filesystem_remove' is not defined

location: <unknown location>:-1
```
EDIT
i alo tried installing the zip and it does show, but again same error of course

**Comment by BlendingJake** [comment]
Sorry about the delay in getting back.

@schroef The reason you didn't get `JARCH-Vis.2.0.0` is because you cloned the `restructure` branch instead of downloading the most recent release. This is also why you got an error when you tried to install. `restructure` is a branch that I'm trying some features out on that may or may not ever make it into the master version of the add-on. I am testing a Python package called `scipy`, but again, that is a development branch. I'd stick to just downloading from the releases page.

@thmrtnz As to your issue, I plan to look into it more today.

**Comment by BlendingJake** [comment]
@thmrtnz 

I have not been able to replicate your issue. I'm not sure if it is an with the particular build of Blender you are using. Could you try grabbing the newest version of 2.8 and see if the issue persists?

**Comment by thmrtnz** [comment]
@BlendingJake I think the culprit is "Archive Utility.app" from macOS. It adds a hidden .0 extension to the extracted folder' name. macOS users may encounter this issue or not. It happened two times on my machine. But it works fine once I removed the .0 extension.

**Comment by BlendingJake** [comment]
@thmrtnz I just realized that you basically said this a couple of replies ago. I misunderstood that reply.

Glad to hear it is working.

The `.0` extension may be getting added because the original `.zip` file name ends with `.0`. Renaming before extracting might solve that issue. Either way, I need to fix the `.zip` file naming to default to `jarch_vis`.
